CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
-- vector extension skipped - install pgvector separately if needed

CREATE TABLE interview_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6),
  interview_time TIMESTAMP(6) NOT NULL,
  interview_type VARCHAR(255),
  interviewer VARCHAR(255),
  meeting_link TEXT,
  notes TEXT,
  "position" VARCHAR(255) NOT NULL,
  round_number INTEGER,
  status VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT interview_schedule_status_check
    CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'RESCHEDULED'))
);

CREATE TABLE resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  analyze_error VARCHAR(500),
  analyze_status VARCHAR(20),
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  original_filename VARCHAR(255) NOT NULL,
  resume_text TEXT,
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT resumes_analyze_status_check
    CHECK (analyze_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_resume_hash UNIQUE (file_hash)
);

CREATE TABLE resume_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analyzed_at TIMESTAMP(6) NOT NULL,
  content_score INTEGER,
  expression_score INTEGER,
  overall_score INTEGER,
  project_score INTEGER,
  skill_match_score INTEGER,
  strengths_json TEXT,
  structure_score INTEGER,
  suggestions_json TEXT,
  summary TEXT,
  resume_id BIGINT NOT NULL,
  CONSTRAINT fkrp4f11h23bp0j118yan185lr5
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

CREATE TABLE interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  current_question_index INTEGER,
  difficulty VARCHAR(16),
  evaluate_error VARCHAR(500),
  evaluate_status VARCHAR(20),
  improvements_json TEXT,
  interview_category VARCHAR(64),
  knowledge_base_id BIGINT,
  llm_provider VARCHAR(50),
  overall_feedback TEXT,
  overall_score INTEGER,
  questions_json TEXT,
  reference_answers_json TEXT,
  resume_id BIGINT,
  session_id VARCHAR(36) NOT NULL,
  skill_id VARCHAR(64),
  source_type VARCHAR(32),
  status VARCHAR(20),
  strengths_json TEXT,
  total_questions INTEGER,
  CONSTRAINT interview_sessions_evaluate_status_check
    CHECK (evaluate_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT interview_sessions_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'EVALUATED')),
  CONSTRAINT uk42bhenf7mu90ochoc1efpg3xa UNIQUE (session_id),
  CONSTRAINT fkhresfe6p1s53klvmqhxxissa2
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

CREATE TABLE interview_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answered_at TIMESTAMP(6) NOT NULL,
  category VARCHAR(255),
  feedback TEXT,
  key_points_json TEXT,
  question TEXT,
  question_index INTEGER,
  reference_answer TEXT,
  score INTEGER,
  user_answer TEXT,
  session_id BIGINT NOT NULL,
  CONSTRAINT uk_interview_answer_session_question UNIQUE (session_id, question_index),
  CONSTRAINT fkjeqvvamvdarrcbswn6kkiuym9
    FOREIGN KEY (session_id) REFERENCES interview_sessions(id)
);

CREATE TABLE knowledge_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  category VARCHAR(100),
  chunk_count INTEGER,
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  name VARCHAR(255) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  question_count INTEGER,
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  vector_error VARCHAR(500),
  vector_status VARCHAR(20),
  CONSTRAINT knowledge_bases_vector_status_check
    CHECK (vector_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_kb_hash UNIQUE (file_hash)
);

CREATE TABLE knowledge_base_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL,
  difficulty VARCHAR(16),
  follow_ups_json TEXT,
  kb_content_hash VARCHAR(64),
  key_points_json TEXT,
  knowledge_base_id BIGINT,
  question TEXT NOT NULL,
  reference_answer TEXT,
  scoring_rubric TEXT,
  skill_id VARCHAR(64) NOT NULL,
  source_context TEXT,
  status VARCHAR(20) NOT NULL,
  topic_summary VARCHAR(300),
  type VARCHAR(64),
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT knowledge_base_questions_status_check
    CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED', 'STALE')),
  CONSTRAINT fkosobqu06r3tbr13ca043slftw
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

CREATE TABLE llm_global_setting (
  id BIGINT NOT NULL PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  default_chat_provider_id VARCHAR(64) NOT NULL,
  default_embedding_provider_id VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE llm_provider_config (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  api_key_ciphertext VARCHAR(4096) NOT NULL,
  api_key_nonce VARCHAR(64) NOT NULL,
  base_url VARCHAR(512) NOT NULL,
  builtin BOOLEAN NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  embedding_dimensions INTEGER,
  embedding_model VARCHAR(128),
  enabled BOOLEAN NOT NULL,
  model VARCHAR(128) NOT NULL,
  supports_embedding BOOLEAN NOT NULL,
  temperature DOUBLE PRECISION,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE rag_chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  is_pinned BOOLEAN DEFAULT false,
  message_count INTEGER,
  status VARCHAR(20),
  title VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT rag_chat_sessions_status_check
    CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE rag_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed BOOLEAN,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  message_order INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP(6),
  session_id BIGINT NOT NULL,
  CONSTRAINT rag_chat_messages_type_check
    CHECK (type IN ('USER', 'ASSISTANT')),
  CONSTRAINT fkfohypaygc0qfqo62vyaxlbntn
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id)
);

CREATE TABLE rag_session_knowledge_bases (
  session_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  PRIMARY KEY (session_id, knowledge_base_id),
  CONSTRAINT fkqfob368wcvb82elsjkx2troqu
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id),
  CONSTRAINT fkjsfwqyt1ntgr0fcvjieq8c0nb
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

-- vector_store table skipped - install pgvector separately if needed


CREATE TABLE voice_interview_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  improvements_json TEXT,
  interview_date TIMESTAMP(6),
  interviewer_role VARCHAR(255),
  overall_feedback TEXT,
  overall_score INTEGER,
  question_evaluations_json TEXT,
  reference_answers_json TEXT,
  session_id BIGINT,
  strengths_json TEXT,
  CONSTRAINT ukijx8aelak8vqf9n4to88qqrna UNIQUE (session_id)
);

CREATE TABLE voice_interview_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_generated_text TEXT,
  created_at TIMESTAMP(6),
  message_type VARCHAR(255) NOT NULL,
  phase VARCHAR(255),
  sequence_num INTEGER,
  session_id BIGINT,
  "timestamp" TIMESTAMP(6),
  user_recognized_text TEXT,
  CONSTRAINT voice_interview_messages_phase_check
    CHECK (phase IN ('INTRO', 'TECH', 'PROJECT', 'HR', 'COMPLETED'))
);

CREATE TABLE voice_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actual_duration INTEGER,
  created_at TIMESTAMP(6),
  current_phase VARCHAR(255),
  custom_jd_text TEXT,
  difficulty VARCHAR(16),
  end_time TIMESTAMP(6),
  evaluate_error VARCHAR(500),
  evaluate_status VARCHAR(255),
  hr_enabled BOOLEAN,
  intro_enabled BOOLEAN,
  llm_provider VARCHAR(50),
  paused_at TIMESTAMP(6),
  planned_duration INTEGER,
  project_enabled BOOLEAN,
  resume_id BIGINT,
  resumed_at TIMESTAMP(6),
  role_type VARCHAR(255) NOT NULL,
  skill_id VARCHAR(64),
  start_time TIMESTAMP(6),
  status VARCHAR(255),
  tech_enabled BOOLEAN,
  updated_at TIMESTAMP(6),
  user_id VARCHAR(255),
  CONSTRAINT voice_interview_sessions_current_phase_check
    CHECK (current_phase IN ('INTRO', 'TECH', 'PROJECT', 'HR', 'COMPLETED')),
  CONSTRAINT voice_interview_sessions_evaluate_status_check
    CHECK (evaluate_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT voice_interview_sessions_status_check
    CHECK (status IN ('IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_interview_answer_session_question
  ON interview_answers (session_id, question_index);
CREATE INDEX idx_interview_session_resume_created
  ON interview_sessions (resume_id, created_at);
CREATE INDEX idx_interview_session_resume_status_created
  ON interview_sessions (resume_id, status, created_at);
CREATE INDEX idx_interview_session_skill_created
  ON interview_sessions (skill_id, created_at);
CREATE INDEX idx_kb_category
  ON knowledge_bases (category);
CREATE INDEX idx_kb_question_kb_status
  ON knowledge_base_questions (knowledge_base_id, status);
CREATE INDEX idx_kb_question_skill_difficulty
  ON knowledge_base_questions (skill_id, difficulty);
CREATE INDEX idx_rag_message_order
  ON rag_chat_messages (session_id, message_order);
CREATE INDEX idx_rag_message_session
  ON rag_chat_messages (session_id);
CREATE INDEX idx_rag_session_updated
  ON rag_chat_sessions (updated_at);

COMMENT ON COLUMN interview_sessions.interview_category IS '知识库面试方向（来自题库 category，普通面试为 NULL）';
